# TCL File Generated by Component Editor 18.1
# Sun Aug 29 09:53:20 CEST 2021
# DO NOT MODIFY


# 
# DDR3_manager "DDR3_manager" v2.0
# Andrea Savarese 2021.08.29.09:53:20
# It takes a 32 bit word from a show-ahead FIFO and send it to SDRAM
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DDR3_manager
# 
set_module_property DESCRIPTION "It takes a 32 bit word from a show-ahead FIFO and send it to SDRAM"
set_module_property NAME DDR3_manager
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Andrea Savarese"
set_module_property DISPLAY_NAME DDR3_manager
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Event_data_to_DDR3
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Event_data_to_DDR3.vhd VHDL PATH src/Event_data_to_DDR3.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter BASE_ADDRESS_RESERVED_MEMORY STRING 000000110000000000000000000000 ""
set_parameter_property BASE_ADDRESS_RESERVED_MEMORY DEFAULT_VALUE 000000110000000000000000000000
set_parameter_property BASE_ADDRESS_RESERVED_MEMORY DISPLAY_NAME BASE_ADDRESS_RESERVED_MEMORY
set_parameter_property BASE_ADDRESS_RESERVED_MEMORY WIDTH ""
set_parameter_property BASE_ADDRESS_RESERVED_MEMORY TYPE STRING
set_parameter_property BASE_ADDRESS_RESERVED_MEMORY UNITS None
set_parameter_property BASE_ADDRESS_RESERVED_MEMORY DESCRIPTION ""
set_parameter_property BASE_ADDRESS_RESERVED_MEMORY HDL_PARAMETER true
add_parameter AMOUNT_OF_RESERVED_MEMORY STRING 000001000000000000000000000000
set_parameter_property AMOUNT_OF_RESERVED_MEMORY DEFAULT_VALUE 000001000000000000000000000000
set_parameter_property AMOUNT_OF_RESERVED_MEMORY DISPLAY_NAME AMOUNT_OF_RESERVED_MEMORY
set_parameter_property AMOUNT_OF_RESERVED_MEMORY TYPE STRING
set_parameter_property AMOUNT_OF_RESERVED_MEMORY UNITS None
set_parameter_property AMOUNT_OF_RESERVED_MEMORY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK_DDR3 clk Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master addr_DDR3 address Output 32
add_interface_port avalon_master read_DDR3 read Output 1
add_interface_port avalon_master read_data_DDR3 readdata Input 32
add_interface_port avalon_master write_DDR3 write Output 1
add_interface_port avalon_master write_data_DDR3 writedata Output 32
add_interface_port avalon_master byte_enable_DDR3 byteenable Output 4
add_interface_port avalon_master wait_request_DDR3 waitrequest Input 1
add_interface_port avalon_master burstcount_DDR3 burstcount Output 8
add_interface_port avalon_master read_data_valid_DDR3 readdatavalid Input 1


# 
# connection point conduit_FIFO
# 
add_interface conduit_FIFO conduit end
set_interface_property conduit_FIFO associatedClock clock
set_interface_property conduit_FIFO associatedReset reset
set_interface_property conduit_FIFO ENABLED true
set_interface_property conduit_FIFO EXPORT_OF ""
set_interface_property conduit_FIFO PORT_NAME_MAP ""
set_interface_property conduit_FIFO CMSIS_SVD_VARIABLES ""
set_interface_property conduit_FIFO SVD_ADDRESS_GROUP ""

add_interface_port conduit_FIFO FIFO_ack data_ack Output 1
add_interface_port conduit_FIFO FIFOevents_data data_event Input 32
add_interface_port conduit_FIFO FIFOevents_empty data_empty Input 1


# 
# connection point conduit_sync_and_ctrl
# 
add_interface conduit_sync_and_ctrl conduit end
set_interface_property conduit_sync_and_ctrl associatedClock clock
set_interface_property conduit_sync_and_ctrl associatedReset reset
set_interface_property conduit_sync_and_ctrl ENABLED true
set_interface_property conduit_sync_and_ctrl EXPORT_OF ""
set_interface_property conduit_sync_and_ctrl PORT_NAME_MAP ""
set_interface_property conduit_sync_and_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property conduit_sync_and_ctrl SVD_ADDRESS_GROUP ""

add_interface_port conduit_sync_and_ctrl fpga_side_RAM_ctrl_reg fpga_side_reg Output 32
add_interface_port conduit_sync_and_ctrl hps_side_RAM_ctrl_reg hps_side_reg Input 32
add_interface_port conduit_sync_and_ctrl enable_writing enable Input 1

